### ISSUE TITLE
Bash Script installation not working

### ISSUE THREAD

**Issue by yashppawar** [Shravan-1908/hydra#3]
I have tried installing hydra via the bash script in the README on Ubuntu and Pop OS, but it is not getting installed with the script.

**Comment by Shravan-1908** [comment]
Can you share the log of the terminal when you executed the installation script?

**Comment by arghyagod-coder** [comment]
Tried the relogin?

**Comment by Shravan-1908** [comment]
@yashppawar Can you trying running following commands:
```bash
$ curl https://raw.githubusercontent.com/Shravan-1908/hydra/main/linux_install.sh > hydra_install.sh
$ chmod +x ./hydra_install.sh
$ bash ./hydra_install.sh
```

Restart the shell and it might work this time.

**Comment by yashppawar** [comment]
Worked fine, thank you @Shravan-1908 for your help and for creating a project like `hydra`
